apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-deployment
  labels:
    app: amazon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazon
  template:
    metadata:
      labels:
        app: amazon
    spec:
      containers:
      - name: amazon-container
        image: aravindh07/amazon:latest  # Placeholder - will be replaced by Jenkins
        ports:
        - containerPort: 3000
