apiVersion: v1
kind: Service
metadata:
  name: amazon-service
  labels:
    app: amazon
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: amazon
  type: NodePort  # For Minikube
